language:  python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
script:
  - make test
deploy:
  provider: heroku
  app: gentle-reef-50143
  api_key: ${HEROKU_API_KEY}
